### ISSUE TITLE
Move example specs to common repo?

### ISSUE THREAD

**Issue by RussellSprouts** [vega/vega-editor#39]
In [this](https://github.com/vega/vega/pull/498) pull request we had an issue because the example specs in Vega's test directory are out of sync with the examples in this repository. We already have a vega-datasets repo. It may be beneficial to move our example specs to a common repository (vega-examples?). That way we don't have broken specs lurking in our repositories which people may try to use.

**Comment by domoritz** [comment]
As an alternative, the specs could live in the vega repo and we copy them. This is the approach we want to use for vega-lite examples.

**Comment by arvind** [comment]
I'm not sure there's a perfect solution here. I was iffy about extracting vega-datasets to a standalone repository, and I'm even more iffy about doing it for specs. Some issues to contend with:

1. Making it much more difficult for end users to find example specifications and datasets. There's already unexpected complexity here that was introduced by extracting vega-datasets -- the components for our canonical examples are scattered across multiple repositories. As a result, users must manually hunt them down and reassemble them. Moving to a vega-examples would exacerbate this problem. 

2. Unit tests and example specifications are not a 1-1 correspondence. For example, there are several Vega test specifications for tree layouts that aren't sufficiently polished to feature as part of the public facing editor. Differentiating this within an external repository adds another layer of complexity for unclear advantages. 

3. Having unit tests rely on external dependencies ("external" from the point of view of individual projects, rather than ownership) is dangerous. I do not want the build to break because a change is introduced to either vega-datasets or vega-examples and isn't accounted for in the unit tests.

**Comment by domoritz** [comment]
To solve #2, we annotated examples in the vega-lite repo. https://github.com/vega/vega-lite/blob/master/examples/vlexamples.json#L6

**Comment by kanitw** [comment]
> To solve 2., we annotated examples in the vega-lite repo. https://github.com/vega/vega-lite/blob/master/examples/vlexamples.json#L6

Actually annotation only solves part of the problem.  We also have other unpolished specs included in the unit tests.

**Comment by arvind** [comment]
Yes, I am aware that one can address the above points programmatically. My point was that doing so introduces a lot more complexity (and more points of failure), and it is unclear to me whether the advantages are commensurate. Regardless of the specific outcome of this issue, I think all our projects should adopt a consistent method for exposing/publishing examples -- i.e., the absolute worst outcome in my mind is for canonical Vega examples to be accessible and live in one place, and for Vega-Lite examples to be found in another.

**Comment by kanitw** [comment]
FYI, currently we put all Vega-Lite examples in Vega-Lite repo mainly because we can validate both input specs (VL) and compiled specs (VG) in our continuous test.   (And putting examples outside our repo is basically flaw No. 3 that Arvind mentions above.)

**Comment by kanitw** [comment]
> Regardless of the specific outcome of this issue, I think all our projects should adopt a consistent method for exposing/publishing examples 

For consistency, how about  putting Vega examples in `examples/` in the Vega repo (like we do)? 
While datasets should be consistent between VL and VG, Vega examples do not need to be in sync with VL at all, so keeping it in Vega repo might reduce the problem that @RussellSprouts mention above without a burden of another repo and also make it consistent with VL. 

For VL, we should validate all of compiled examples anyway, so we want to have a copy of it inside VL repo and we are planning to have some script for copying them to Vega Editor.

**Comment by domoritz** [comment]
+1

**Comment by arvind** [comment]
There is no urgency to change the status quo for Vega. We can re-evaluate things once Vega-Lite hits 1.0, and we have the proposed script built and tested. Until such a time, it is difficult for me to evaluate the complexity such a process introduces for either us or for our users. For example are example specifications going to be published as part of each release, and copied over by vega-editor's vendor script? Or, is copying over examples part of the Vega-Lite deployment process? This would imply that deploying our projects are less decoupled than they are now. This decoupling has come in handy in the past when, for example, a newer version of Vega was published to npm but we held back on deploying it to the editor due to incompatibilities with Vega-Lite. 

I'm going to close this issue for now, because I think we have bigger fish to fry. As I said, let's revisit this issue closer to Vega-Lite's release.
