### ISSUE TITLE
crossfilter example: resetting visualization programatically makes charts disappear 

### ISSUE THREAD

**Issue by cchandurkar** [vega/vega-editor#44]
I have been trying to update the state of visualization dynamically by firing signals. For example: to reset Time of Day chart I fired signals as `timesStart: null, timesEnd: null, minTime: -1, maxTime: -1` which work just fine. It also works for Delay and Distance charts. But when it comes to Date chart firing `dayStart`, `dayEnd`, `minDay` and `maxDay` signals as above would just make rest of the 3 chart disappear. 

Is it the way it is supposed to work? What is the best approach to reset any visualization?

![screenshot from 2016-01-28 01 04 24](https://cloud.githubusercontent.com/assets/2879791/12636477/2d4f3b68-c55b-11e5-8668-65c8e84ecba1.png)

**Comment by arvind** [comment]
Hi @cchandurkar, thanks for filing the issue. The bug was in how the `maxDay` signal was constructed -- if both `dayStart` and `dayEnd` were `null` or `0`, then `maxDay` would evaluate to `0`. I've fixed this with 6620cfb, and you should see the results live sometime next week. Your approach for firing signals is indeed the correct way to reset interactive behaviours.
