### ISSUE TITLE
Add "are you sure you want to navigate away" popup when custom editor is in non-empty state

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega-editor#48]
An accidental navigation currently wipes out what you were working on. Seems relatively straightforward, though you would need to continually check which state you are in and set/unset the callback accordingly:

http://stackoverflow.com/questions/1119289/how-to-show-the-are-you-sure-you-want-to-navigate-away-from-this-page-when-ch

**Comment by domoritz** [comment]
The editor stores the spec you are editing in local storage so you should see it when you load the page again. To try this, do the following:

* Go to https://vega.github.io/vega-editor/?mode=vega&spec=bar
* Change the spec, parse it. Note how the editor switches to "Custom"
* Now close the tab
* Open https://vega.github.io/vega-editor/?mode=vega
* You should see the same visualization that you were working on

Note that we only load from local storage when you load the editor initially. You may need to refresh in the page when you are on "Custom" to see it. Also, you can delete the content by parsing an empty spec.

**Comment by domoritz** [comment]
Having said that, we could still add the popup but I feel it could quickly become annoying. We should definitely show it when you edited a visualization but have not parsed (and thus saved it in local storage).

**Comment by kanitw** [comment]
How expensive is the storing process?  Another idea is saving the spec on change rather than on parse?

**Comment by kanitw** [comment]
That way, we don't need the popup at all?

**Comment by domoritz** [comment]
Should be fine. But it's odd to save a state that is inconsistent (does not parse). 

As discussed with @arvind, there are some more issues around the UX of this feature. We have to a) make it obvious that we restored a spec b) make it easier to clear the spec from local storage.

The easiest solution is a button [clear stored spec].

**Comment by arvind** [comment]
Another option is the "Saving..." text you see in Google Docs, so that we can make clear _when_ the save is happening. If a user hovered over it, perhaps it would switch to "Clear Saved Spec", or even allow them to disable this feature entirely. 

Loading the saved state should likely be a little smarter too. For instance, I repeatedly find it confusing when I load the editor and find an old spec automatically loaded. Perhaps we store the timestamp as well and only reload the spec automatically if it's e.g., within the same hour/day. If we went down the "Saving..." text route, then this UI element could double to say "Load Saved State" if a saved state is present but falls outside the timeout.

**Comment by kanitw** [comment]
Future Idea:  with a timestamp, we can even save _n_ (10?) last specs parsed and load older ones -- probably useful when you're testing a few specs.

**Comment by domoritz** [comment]
in #133
