### ISSUE TITLE
Embed Vega-Editor in Electron

### ISSUE THREAD

**Issue by kanitw** [vega/vega-editor#49]
(Or maybe just make an electron Vega/Vega-Lite offline viewer)

This is possibly a good task for undergrad or external contributors.

**Comment by domoritz** [comment]
Who wants this? I'm not trying to be annoying but I haven't heard anyone wanting this yet.

**Comment by kanitw** [comment]
Krist and Matt both say the same thing.   I don't think we should do thing ourselves, but rather than a potential task for external contributors.

**Comment by domoritz** [comment]
Okay. I think this should come together with other ide like features such as saving specs and better debugging capabilities.

**Comment by randyzwitch** [comment]
It's actually < 10 LOC to change this repo to an Electron app, but fairly sure that the changes break the functionality of the currently existing site (my quick hack doesn't handle to back-and-forth between vega and vega-lite, only vega renders). 

Not sure it makes sense for you folks to accept a PR here, as the changes are just slight enough where you (probably) can't import vega-editor as a submodule, and you don't really get any benefit over just running `npm start` against Python SimpleHttpServer.

I can gist the code if you are interested though.

**Comment by mathisonian** [comment]
Hey @randyzwitch, I'm working on re-architecting some things with this repo that may potentially change how this would best integrate with an electron app, but would love to see a gist of what you had to update.

**Comment by randyzwitch** [comment]
https://github.com/randyzwitch/vega-editor/commit/b4b5c0bbe3aa38a3e2aa181e611fe2a1b3f12de8

Couple things to keep in mind:
- Today is the first time that I played with Electron, so this might not be the canonical way to do this. But if you do `npm install && npm start`, it should build and open in an Electron window

- I don't know JavaScript! (This is semi-embarrassing, given that I maintain the Vega library in Julia). Because of this, I didn't fix the issue with vega-lite not working, but vega loaded just fine and rendered inside of Electron

As you can see, the only real change I made was to add the `main.js` file, which is a literal copy-paste from the Electron doc example. `d3` doesn't export a global in Electron, so I needed to define that, and I added a few lines in `package.json`

Surprisingly easy, but after playing with it for 10-15 minutes, I'm not sure I see a use case as-is for Electron over the Python webserver method.

**Comment by kanitw** [comment]
> Surprisingly easy, but after playing with it for 10-15 minutes, I'm not sure I see a use case as-is for Electron over the Python webserver method.

If you can double click to open a Vega visualization file as compared to type SimpleHTTPServer and copy the code over every time, that's already pretty neat.

**Comment by domoritz** [comment]
Not needed. Better use vscode and @kristw's viewer.

**Comment by kanitw** [comment]
https://github.com/kristw/vega-desktop
